Math worlds main page
mathworlds/site pull request #19
Opened 2022-05-23 02:34 UTC by CriticalWasTaken

2022-05-23 04:57 UTC, dubinsky requested changes

2022-05-23 04:57 UTC, dubinsky commented on blog_page.css
> +}
please add a newline character at the end of the file

2022-05-23 04:57 UTC, dubinsky commented on blog_page.html
> +</html>
newline

2022-05-23 04:57 UTC, dubinsky commented on index.html
> +</html>
newline

2022-05-23 04:57 UTC, dubinsky commented on main.css
> +}
newline

2022-05-27 18:11 UTC, CriticalWasTaken commented
New lines added, this code should be ready for deployment.

2022-05-27 22:07 UTC, dubinsky approved these changes

2022-05-27 22:08 UTC, merged